import type { ReactNode } from 'react'
import { CalendarDays, Check, CircleDollarSign, CreditCard, Info, ReceiptText, ShieldCheck, Sparkles } from 'lucide-react'
import { PortalCalculationSkeleton, PortalSkeleton } from '@/components/portal/PortalUI'
import { calculateLuxorPaymentSchedule } from '@/lib/luxorPaymentSchedule'
import type { LuxorPaymentInstallment, LuxorProposalPaymentPlan } from '@/lib/luxorInquiryTypes'

type DateValue = string | null | undefined
export type ProposalPaymentScheduleProps = {
  finalEventPrice?: number | null
  venueServicesTotal?: number | null
  eventServicesTotal?: number | null
  refundableSecurityDeposit?: number | null
  paymentPlan?: Partial<LuxorProposalPaymentPlan> | null
  finalPaymentDueDate?: DateValue
  eventDate?: DateValue
  bookingDate?: DateValue
  paymentCount?: number | null
  editable?: boolean
  onPaymentCountChange?: (count: 2 | 3 | 4 | 5) => void
  installments?: LuxorPaymentInstallment[] | null
  eventServicesPaymentNote?: string | null
  className?: string
}
export type ProposalPaymentScheduleRow = { id: string; number: number; label?: string; description: string; dueDate: string | null; dueTiming: 'after_signature' | 'final_due_date' | 'not_due'; amount: number; collection: string }
export type ProposalPaymentScheduleCalculation = { finalEventPrice: number | null; venueServicesTotal: number | null; eventServicesTotal: number | null; refundableSecurityDeposit: number; initialContractPayment: number | null; finalEventBalance: number | null; amountDueAfterSignature: number | null; finalPaymentDueDate: string | null; rows: ProposalPaymentScheduleRow[]; errors: string[] }

const moneyFormatter = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2, maximumFractionDigits: 2 })
const dateFormatter = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' })
const counts: Array<2 | 3 | 4 | 5> = [2, 3, 4, 5]
const sequenceLabels: Record<2 | 3 | 4 | 5, string> = {
  2: 'Venue Services → Event Services',
  3: 'Venue Services → Event Services × 2',
  4: '25% Venue Deposit → Remaining Venue Services → Event Services × 2',
  5: '25% Venue Deposit → Remaining Venue Services → Event Services × 3',
}
const money = (value: number | null | undefined) => typeof value === 'number' && Number.isFinite(value) ? moneyFormatter.format(value) : '—'
const date = (value: string | null | undefined) => { if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return null; const [y, m, d] = value.split('-').map(Number); return dateFormatter.format(new Date(Date.UTC(y, m - 1, d))) }
const today = () => new Date().toISOString().slice(0, 10)

export function calculateProposalPaymentSchedule(input: ProposalPaymentScheduleProps): ProposalPaymentScheduleCalculation {
  const finalEventPrice = typeof input.finalEventPrice === 'number' ? input.finalEventPrice : null
  const venue = typeof input.venueServicesTotal === 'number' ? input.venueServicesTotal : null
  const event = typeof input.eventServicesTotal === 'number' ? input.eventServicesTotal : null
  const empty = (errors: string[]): ProposalPaymentScheduleCalculation => ({ finalEventPrice, venueServicesTotal: venue, eventServicesTotal: event, refundableSecurityDeposit: input.refundableSecurityDeposit ?? 750, initialContractPayment: null, finalEventBalance: null, amountDueAfterSignature: null, finalPaymentDueDate: null, rows: [], errors })
  if (finalEventPrice === null || venue === null || event === null || !input.eventDate) return empty(['Complete event details and pricing to calculate the payment schedule.'])
  const schedule = calculateLuxorPaymentSchedule({ eventDate: String(input.eventDate).slice(0, 10), bookingDate: String(input.bookingDate || input.paymentPlan?.booking_date || today()).slice(0, 10), venueServicesTotal: venue, eventServicesTotal: event, paymentCount: input.paymentCount ?? input.paymentPlan?.payment_count ?? 4 })
  if (!schedule) return empty(['The event date is too close to the final-payment deadline for a payment schedule.'])
  return { finalEventPrice, venueServicesTotal: venue, eventServicesTotal: event, refundableSecurityDeposit: input.refundableSecurityDeposit ?? 750, initialContractPayment: schedule.booking_payment, finalEventBalance: schedule.remaining_event_balance, amountDueAfterSignature: schedule.booking_payment, finalPaymentDueDate: schedule.final_payment_due_date, rows: schedule.rows.map((row) => ({ id: `installment-${row.installment_order}`, number: row.installment_order, label: row.label, description: row.description, dueDate: row.due_at, dueTiming: row.installment_order === 1 ? 'after_signature' : 'final_due_date', amount: row.amount, collection: 'Stripe after signature' })), errors: schedule.warnings }
}

function FinancialStat({ icon, label, value, detail, highlighted, loading }: { icon: ReactNode; label: string; value: string; detail: string; highlighted?: boolean; loading?: boolean }) {
  return <div className={`min-w-0 rounded-xl border p-4 ${highlighted ? 'border-[#caa24c]/40 bg-[#caa24c]/[0.08]' : 'border-[color:var(--portal-border)] bg-[color:var(--portal-card)]'}`}><div className="flex items-center gap-2 text-[color:var(--portal-muted)]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[color:var(--portal-soft)] text-[#8c6529] dark:text-[#f1d27a]">{icon}</span><p className="text-[9px] font-black uppercase tracking-[0.12em]">{label}</p></div>{loading ? <PortalSkeleton className="mt-3 h-7 w-28 rounded" /> : <p className={`mt-3 font-mono text-2xl font-black tabular-nums ${highlighted ? 'text-[#8c6529] dark:text-[#f1d27a]' : 'text-[color:var(--portal-text)]'}`}>{value}</p>}<p className="mt-1 text-[11px] leading-4 text-[color:var(--portal-muted)]">{detail}</p></div>
}

export function ProposalPaymentSchedule({ finalEventPrice, venueServicesTotal, eventServicesTotal, refundableSecurityDeposit = 750, paymentPlan, eventDate, bookingDate, paymentCount, editable = false, onPaymentCountChange, installments, eventServicesPaymentNote, className = '' }: ProposalPaymentScheduleProps) {
  const schedule = calculateProposalPaymentSchedule({ finalEventPrice, venueServicesTotal, eventServicesTotal, refundableSecurityDeposit, paymentPlan, eventDate, bookingDate, paymentCount })
  const selectedCount = (schedule.rows.length || paymentCount || paymentPlan?.payment_count || 4) as 2 | 3 | 4 | 5
  const availability = eventDate ? calculateLuxorPaymentSchedule({ eventDate: String(eventDate).slice(0, 10), bookingDate: String(bookingDate || paymentPlan?.booking_date || today()).slice(0, 10), venueServicesTotal: venueServicesTotal || 0, eventServicesTotal: eventServicesTotal || 0, paymentCount: selectedCount }) : null
  const available = availability?.available_counts || []
  // An empty list means either the date inputs are not ready yet or the event
  // is inside the 60-day deadline. Once both dates are known, hide every
  // payment-count option when no schedule can legally fit.
  const availabilityKnown = Boolean(eventDate && (bookingDate || paymentPlan?.booking_date))
  const loading = schedule.finalEventPrice === null
  const persistedByOrder = new Map((installments || []).map((item) => [item.installment_order, item]))
  return <section aria-label="Proposal payment plan" className={`space-y-5 ${className}`.trim()}>
    <header className="flex flex-col gap-4 rounded-2xl border border-[color:var(--portal-border)] bg-[color:var(--portal-card)] p-5 sm:flex-row sm:items-start sm:justify-between sm:p-6"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] text-[#a8792f] dark:text-[#caa24c]">Your payment plan</p><h3 className="mt-2 max-w-2xl font-serif text-3xl font-semibold leading-tight text-[color:var(--portal-text)]">Simple, flexible payments designed around your event.</h3><p className="mt-3 text-sm leading-6 text-[color:var(--portal-muted)]">Venue Services are paid first, then payments go toward Event Services.</p></div>{eventDate ? <div className="rounded-xl border border-[#caa24c]/25 bg-[#caa24c]/[0.055] p-4 sm:min-w-[245px]"><p className="text-[9px] font-black uppercase tracking-[0.13em] text-[color:var(--portal-muted)]">Event date</p><p className="mt-2 text-sm font-bold text-[color:var(--portal-text)]"><CalendarDays size={16} className="mr-2 inline text-[#8c6529] dark:text-[#f1d27a]" />{date(String(eventDate).slice(0, 10)) || 'Set event date'}</p><p className="mt-2 text-xs leading-5 text-[#8c6529] dark:text-[#f1d27a]">Final payment is due 60 days before your event.</p></div> : null}</header>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><FinancialStat icon={<ReceiptText size={16} />} label="Event Total" value={money(schedule.finalEventPrice)} detail="Total investment" highlighted loading={loading} /><FinancialStat icon={<CalendarDays size={16} />} label="Due at signing" value={money(schedule.initialContractPayment)} detail="Booking payment" loading={loading} /><FinancialStat icon={<CircleDollarSign size={16} />} label="Remaining balance" value={money(schedule.finalEventBalance)} detail="Balance after booking payment" loading={loading} /><FinancialStat icon={<CreditCard size={16} />} label="Scheduled payments" value={schedule.rows.length ? String(schedule.rows.length) : '—'} detail="Total event payments" loading={loading} /></div>
    <div className="flex gap-3 rounded-xl border border-[#caa24c]/25 bg-[#caa24c]/[0.055] p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#caa24c]/12 text-[#8c6529] dark:text-[#f1d27a]"><ShieldCheck size={17} /></span><div><p className="text-sm font-bold text-[color:var(--portal-text)]">Security Deposit: {money(refundableSecurityDeposit)}</p><p className="mt-1 text-xs leading-5 text-[color:var(--portal-muted)]">Refundable deposit due 30 days before your event. It is separate from your Event Total and returned after the event, subject to inspection and the Event Agreement.</p></div></div>
    <section className="rounded-2xl border border-[color:var(--portal-border)] bg-[color:var(--portal-card)] p-5 sm:p-6"><div className="flex items-center gap-3"><CalendarDays size={20} className="text-[#8c6529] dark:text-[#f1d27a]" /><div><p className="text-[10px] font-black uppercase tracking-[0.13em] text-[#8c6529] dark:text-[#f1d27a]">Choose your payment schedule</p><p className="mt-1 text-sm text-[color:var(--portal-muted)]">Choose how the Event Total is divided between Venue Services and Event Services.</p></div></div><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{counts.map((count) => { const enabled = !availabilityKnown || available.includes(count); const active = selectedCount === count; return <button key={count} type="button" disabled={!editable || !enabled} onClick={() => onPaymentCountChange?.(count)} className={`min-h-12 rounded-xl border px-3 text-left transition ${active ? 'border-[#caa24c] bg-[#caa24c] text-white shadow-sm shadow-[#caa24c]/20' : 'border-[color:var(--portal-border)] bg-[color:var(--portal-soft)] text-[color:var(--portal-text)]'} ${!enabled ? 'cursor-not-allowed opacity-35' : editable ? 'cursor-pointer hover:border-[#dfbd68] hover:bg-[#dfbd68]' : 'cursor-default'}`}><span className="flex items-center justify-between text-sm font-bold">{active ? <span className="inline-flex items-center gap-2"><Check size={15} className="text-white" />{count} Payments</span> : `${count} Payments`}</span><span className={`mt-1 block text-[10px] leading-4 ${active ? 'text-white/85' : 'text-[color:var(--portal-muted)]'}`}>{sequenceLabels[count]}</span></button> })}</div></section>
    <section className="overflow-hidden rounded-2xl border border-[color:var(--portal-border)] bg-[color:var(--portal-card)]"><div className="border-b border-[color:var(--portal-border)] px-5 py-4"><p className="text-[10px] font-black uppercase tracking-[0.13em] text-[#8c6529] dark:text-[#f1d27a]">Your {selectedCount}-payment schedule</p><p className="mt-1 text-xs text-[color:var(--portal-muted)]">The final payment is always due 60 days before the event.</p></div>{loading ? <div className="p-5"><PortalCalculationSkeleton label="Calculating payment schedule" rows={4} /></div> : <div className="divide-y divide-[color:var(--portal-border)]">{schedule.rows.map((row) => { const persisted = persistedByOrder.get(row.number); const status = persisted?.status || 'scheduled'; const statusLabel = status === 'paid' ? 'Paid' : status === 'partial' ? 'Partial' : status === 'void' ? 'Voided' : 'Pending'; const dueAfterSignature = row.number === 1; return <div key={row.id} className="grid gap-3 px-5 py-4 sm:grid-cols-[64px_1fr_210px_130px] sm:items-center"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#171512] font-mono text-sm font-black text-white">{row.number}</span><div><p className="text-sm font-bold uppercase text-[color:var(--portal-text)]">{row.label}</p><p className="mt-1 text-xs text-[color:var(--portal-muted)]">{row.description}{dueAfterSignature ? ' · Due after agreement signature' : ''}{persisted?.payment_method ? ` · ${persisted.payment_method}` : ''}</p></div><div><p className="text-xs font-semibold text-[color:var(--portal-text)]">{row.dueDate ? date(row.dueDate) : 'Set due date'}</p><p className={`mt-1 text-[10px] font-bold uppercase ${status === 'paid' ? 'text-emerald-700 dark:text-emerald-300' : status === 'partial' ? 'text-amber-700 dark:text-amber-300' : 'text-[color:var(--portal-muted)]'}`}>{statusLabel}{persisted?.paid_at ? ` · ${date(persisted.paid_at.slice(0, 10))}` : ''}</p></div><p className="font-mono text-xl font-black tabular-nums text-[#8c6529] dark:text-[#f1d27a] sm:text-right">{money(row.amount)}</p></div>})}</div>}<div className="grid gap-4 border-t border-[color:var(--portal-border)] bg-[#caa24c]/[0.045] px-5 py-4 sm:grid-cols-2 sm:items-center"><div><p className="text-[9px] font-black uppercase tracking-[0.13em] text-[color:var(--portal-muted)]">Total investment</p><p className="mt-1 font-mono text-2xl font-black text-[#8c6529] dark:text-[#f1d27a]">{money(schedule.finalEventPrice)}</p></div><p className="flex items-center gap-2 text-sm font-semibold text-[color:var(--portal-text)]"><Check className="text-emerald-600" size={18} /> Everything must be paid in full 60 days before your event.</p></div></section>
    <div className="flex gap-3 rounded-xl border border-emerald-500/20 bg-emerald-500/[0.055] p-4"><Sparkles size={18} className="mt-0.5 shrink-0 text-emerald-700 dark:text-emerald-300" /><div><p className="text-sm font-bold text-[color:var(--portal-text)]">Want to pay more, sooner?</p><p className="mt-1 text-xs leading-5 text-[color:var(--portal-muted)]">You can make an additional payment of at least $200 toward your outstanding Event Services balance at any time. It will reduce the balance without creating another scheduled installment.</p></div></div>
    {eventServicesPaymentNote ? <p className="text-xs text-[color:var(--portal-muted)]">{eventServicesPaymentNote}</p> : null}{schedule.errors.length ? <div role="status" className="flex gap-2 rounded-xl border border-amber-500/25 bg-amber-500/[0.07] p-4 text-xs leading-5 text-amber-900 dark:text-amber-100"><Info size={15} className="mt-0.5 shrink-0" /><span>{schedule.errors.join(' ')}</span></div> : null}
  </section>
}
