'use client'

import { useState } from 'react'
import { CreditCard } from 'lucide-react'

type Method = 'card' | 'cash' | 'zelle' | 'check'
type Amount = 'deposit' | 'full'
export function PaymentChoice({ token, deposit, full, initialMethod = 'card', initialAmount = 'deposit' }: { token: string; deposit: number; full: number; initialMethod?: Method; initialAmount?: Amount }) {
  const [method, setMethod] = useState<Method>(initialMethod); const [amount, setAmount] = useState<Amount>(initialAmount); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  const submit = async () => { setBusy(true); setMessage(''); try { const response = await fetch(`/api/public/proposals/${encodeURIComponent(token)}/payment-preference`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ method, amount }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'We could not save your selection.'); if (data.checkoutUrl) window.location.assign(data.checkoutUrl); else setMessage(`Your ${method === 'zelle' ? 'Zelle' : method} preference was sent to Luxor. Your date is not reserved until Luxor confirms payment.`) } catch (error) { setMessage(error instanceof Error ? error.message : 'We could not save your selection.') } finally { setBusy(false) } }
  const label = (value: number) => value.toLocaleString('en-US', { style: 'currency', currency: 'USD' })
  return <section className="mt-8 rounded-2xl border border-[#caa24c]/25 bg-[#caa24c]/[0.07] p-5 sm:p-6"><p className="text-[9px] font-black uppercase tracking-[0.24em] text-[#caa24c]">Choose payment</p><p className="mt-2 text-sm leading-6 text-zinc-200">Choose your preferred method and whether you intend to pay the reservation deposit or the full event balance. Cash, Zelle, and check selections notify Luxor; they do not reserve the date until payment is confirmed.</p><div className="mt-5 grid gap-2 sm:grid-cols-4">{(['card','zelle','cash','check'] as Method[]).map((value) => <button type="button" key={value} onClick={() => setMethod(value)} className={`rounded-xl border px-3 py-3 text-xs font-bold capitalize ${method === value ? 'border-[#caa24c] bg-[#caa24c]/20 text-[#f1d27a]' : 'border-white/10 text-zinc-300'}`}>{value === 'zelle' ? 'Zelle' : value}</button>)}</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => setAmount('deposit')} className={`rounded-xl border p-4 text-left ${amount === 'deposit' ? 'border-[#caa24c] bg-[#caa24c]/20' : 'border-white/10'}`}><span className="block text-xs font-bold text-white">Reservation deposit</span><span className="mt-1 block font-mono text-sm text-[#f1d27a]">{label(deposit)}</span></button><button type="button" onClick={() => setAmount('full')} className={`rounded-xl border p-4 text-left ${amount === 'full' ? 'border-[#caa24c] bg-[#caa24c]/20' : 'border-white/10'}`}><span className="block text-xs font-bold text-white">Full event balance</span><span className="mt-1 block font-mono text-sm text-[#f1d27a]">{label(full)}</span></button></div><button type="button" disabled={busy} onClick={submit} className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#caa24c] px-6 text-xs font-black uppercase tracking-wider text-[#130e08] disabled:opacity-60"><CreditCard size={16}/>{busy ? 'Saving…' : method === 'card' ? 'Continue to Stripe' : 'Send payment preference'}</button>{message ? <p className="mt-3 text-xs leading-5 text-zinc-300">{message}</p> : null}</section>
}
