create table if not exists public.luxor_elena_settings (
  scope text primary key default 'public' check (scope = 'public'),
  draft_instructions jsonb not null default '{}'::jsonb,
  published_instructions jsonb not null default '{}'::jsonb,
  version integer not null default 1 check (version > 0),
  published_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by text
);

create table if not exists public.luxor_elena_knowledge (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(btrim(title)) between 1 and 180),
  content text not null check (char_length(btrim(content)) between 1 and 8000),
  category text not null check (char_length(btrim(category)) between 1 and 100),
  source_type text not null default 'manual' check (source_type in ('manual', 'import', 'website', 'connected')),
  source_label text,
  active boolean not null default false,
  archived boolean not null default false,
  sort_order integer not null default 0,
  published_payload jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text
);

create table if not exists public.luxor_elena_flows (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 1 and 160),
  description text not null default '' check (char_length(description) <= 1000),
  trigger_text text not null default '' check (char_length(trigger_text) <= 1000),
  steps jsonb not null default '[]'::jsonb check (jsonb_typeof(steps) = 'array'),
  active boolean not null default false,
  archived boolean not null default false,
  sort_order integer not null default 0,
  published_payload jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text
);

create table if not exists public.luxor_elena_audit (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text,
  actor_email text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists luxor_elena_knowledge_status_idx
  on public.luxor_elena_knowledge (active, category, sort_order, updated_at desc);
create index if not exists luxor_elena_flows_status_idx
  on public.luxor_elena_flows (active, sort_order, updated_at desc);
create index if not exists luxor_elena_audit_created_idx
  on public.luxor_elena_audit (created_at desc);

alter table public.luxor_elena_settings enable row level security;
alter table public.luxor_elena_knowledge enable row level security;
alter table public.luxor_elena_flows enable row level security;
alter table public.luxor_elena_audit enable row level security;

revoke all on public.luxor_elena_settings from anon, authenticated;
revoke all on public.luxor_elena_knowledge from anon, authenticated;
revoke all on public.luxor_elena_flows from anon, authenticated;
revoke all on public.luxor_elena_audit from anon, authenticated;
grant select, insert, update, delete on public.luxor_elena_settings to service_role;
grant select, insert, update, delete on public.luxor_elena_knowledge to service_role;
grant select, insert, update, delete on public.luxor_elena_flows to service_role;
grant select, insert on public.luxor_elena_audit to service_role;
grant usage, select on sequence public.luxor_elena_audit_id_seq to service_role;

drop trigger if exists luxor_elena_settings_set_updated_at on public.luxor_elena_settings;
create trigger luxor_elena_settings_set_updated_at
  before update on public.luxor_elena_settings
  for each row execute function public.luxor_set_updated_at();

drop trigger if exists luxor_elena_knowledge_set_updated_at on public.luxor_elena_knowledge;
create trigger luxor_elena_knowledge_set_updated_at
  before update on public.luxor_elena_knowledge
  for each row execute function public.luxor_set_updated_at();

drop trigger if exists luxor_elena_flows_set_updated_at on public.luxor_elena_flows;
create trigger luxor_elena_flows_set_updated_at
  before update on public.luxor_elena_flows
  for each row execute function public.luxor_set_updated_at();

insert into public.luxor_elena_settings (scope, draft_instructions, published_instructions, published_at)
values (
  'public',
  jsonb_build_object(
    'identity', 'Elena is the warm public concierge for Luxor Event Space in San Antonio.',
    'introduction', 'Introduce yourself simply as Elena and help visitors plan an event or reserve a private tour.',
    'voice', 'Warm, concise, capable, and low-pressure. Use one or two short sentences and ask at most one useful question at a time.',
    'priorities', 'Answer the visitor first, use current approved facts, and guide qualified visitors toward a private tour or tailored proposal.',
    'accuracy', 'Never invent availability, prices, venue features, policies, services, or confirmation steps. When the answer is not supported, say you want to confirm it with the Luxor team.',
    'tour_guidance', 'Recommend a private tour when it would help the visitor understand fit, layout, packages, or next steps.',
    'clarification', 'Ask one natural clarifying question only when it is needed to provide a useful answer.',
    'handoff', 'Offer human help when information is missing, sensitive, disputed, or requires a promise or exception.'
  ),
  jsonb_build_object(
    'identity', 'Elena is the warm public concierge for Luxor Event Space in San Antonio.',
    'introduction', 'Introduce yourself simply as Elena and help visitors plan an event or reserve a private tour.',
    'voice', 'Warm, concise, capable, and low-pressure. Use one or two short sentences and ask at most one useful question at a time.',
    'priorities', 'Answer the visitor first, use current approved facts, and guide qualified visitors toward a private tour or tailored proposal.',
    'accuracy', 'Never invent availability, prices, venue features, policies, services, or confirmation steps. When the answer is not supported, say you want to confirm it with the Luxor team.',
    'tour_guidance', 'Recommend a private tour when it would help the visitor understand fit, layout, packages, or next steps.',
    'clarification', 'Ask one natural clarifying question only when it is needed to provide a useful answer.',
    'handoff', 'Offer human help when information is missing, sensitive, disputed, or requires a promise or exception.'
  ),
  now()
)
on conflict (scope) do nothing;

with seed(title, content, category, source_type, source_label, active, sort_order) as (
  values
    ('Indoor venue', 'Luxor is one single, fully indoor event venue. The main hall and Luxor Lounge are not weather-dependent. Luxor does not offer an outdoor event space, patio, courtyard, garden, terrace, or open-air option.', 'Venue Information', 'connected', 'Verified venue record', true, 10),
    ('Guest capacity', 'Luxor can accommodate up to 200 people. Do not imply that an exception above 200 guests is available.', 'Capacity', 'connected', 'Verified venue record', true, 20),
    ('Tour length and notice', 'Private tours are 30 minutes, one party per time, and must be requested at least 24 hours ahead. The live booking card is the source of truth for current openings.', 'Tour Information', 'connected', 'Tour availability system', true, 30),
    ('Package options', 'Luxor offers Custom Package, Bronze - Essentials, Silver - Premier, and Gold - All-Inclusive options. Package inclusions vary by the selected package and event details.', 'Packages & Pricing', 'connected', 'Proposal pricing catalog', true, 40),
    ('Exact pricing', 'Rental rates are starting points, not complete event quotes. Exact totals depend on the event date, guest count, rental period, package, selected services, promotions, and tax settings.', 'Packages & Pricing', 'connected', 'Proposal pricing catalog', true, 50),
    ('Venue address', 'Luxor Event Space is located at 803 Castroville Rd #402, San Antonio, TX 78237.', 'Contact Information', 'connected', 'Venue record', true, 60),
    ('Booking email', 'Visitors who need human help can contact booking@luxoratlaspalmas.com.', 'Contact Information', 'connected', 'Venue record', true, 70)
)
insert into public.luxor_elena_knowledge (title, content, category, source_type, source_label, active, sort_order, published_payload, published_at)
select title, content, category, source_type, source_label, active, sort_order,
  jsonb_build_object('title', title, 'content', content, 'category', category, 'source_type', source_type, 'source_label', source_label),
  now()
from seed
where not exists (select 1 from public.luxor_elena_knowledge);

with seed(name, description, trigger_text, steps, active, sort_order) as (
  values
    ('Wedding inquiry', 'Qualify a wedding inquiry and guide the visitor toward a useful next step.', 'Use when a visitor is planning a wedding.', '["Ask for the wedding date if it is not already known.","Ask for the estimated guest count if needed.","Explain relevant current package options.","Recommend a private tour.","Offer to answer one additional question."]'::jsonb, true, 10),
    ('Tour booking', 'Help a visitor find and request a private tour.', 'Use when a visitor asks to visit, tour, schedule, or see availability.', '["Confirm that the visitor wants a private tour.","Use only the current live tour openings.","Direct the visitor to the booking card to select a time and enter contact details.","Explain that tours are 30 minutes and what the visitor can expect."]'::jsonb, true, 20),
    ('Pricing guidance', 'Explain approved pricing without presenting a starting rate as a complete quote.', 'Use when a visitor asks about cost, packages, pricing, or budget.', '["Identify the event type.","Ask for the date or guest count only when needed.","Use the current pricing catalog for approved starting points and package inclusions.","Explain that an exact proposal depends on event selections.","Recommend a tour or tailored proposal."]'::jsonb, true, 30)
)
insert into public.luxor_elena_flows (name, description, trigger_text, steps, active, sort_order, published_payload, published_at)
select name, description, trigger_text, steps, active, sort_order,
  jsonb_build_object('name', name, 'description', description, 'trigger_text', trigger_text, 'steps', steps),
  now()
from seed
where not exists (select 1 from public.luxor_elena_flows);

create or replace function public.luxor_publish_elena_configuration(p_actor text)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  published_time timestamptz := now();
  next_version integer;
begin
  update public.luxor_elena_settings
  set published_instructions = draft_instructions,
      version = version + 1,
      published_at = published_time,
      updated_by = nullif(btrim(p_actor), '')
  where scope = 'public'
  returning version into next_version;

  update public.luxor_elena_knowledge
  set published_payload = case when active and not archived then jsonb_build_object(
        'title', title,
        'content', content,
        'category', category,
        'source_type', source_type,
        'source_label', source_label
      ) else null end,
      published_at = published_time,
      updated_by = nullif(btrim(p_actor), '')
  where id is not null;

  update public.luxor_elena_flows
  set published_payload = case when active and not archived then jsonb_build_object(
        'name', name,
        'description', description,
        'trigger_text', trigger_text,
        'steps', steps
      ) else null end,
      published_at = published_time,
      updated_by = nullif(btrim(p_actor), '')
  where id is not null;

  insert into public.luxor_elena_audit (action, entity_type, entity_id, actor_email, details)
  values ('publish', 'configuration', 'public', nullif(btrim(p_actor), ''), jsonb_build_object('version', next_version));

  return jsonb_build_object('version', next_version, 'published_at', published_time);
end;
$$;

revoke all on function public.luxor_publish_elena_configuration(text) from public, anon, authenticated;
grant execute on function public.luxor_publish_elena_configuration(text) to service_role;

notify pgrst, 'reload schema';
